#!/bin/sh
# title=Format SD Card (exFAT) CAUTION!
# desc=Format the external sd card [exFAT]. This is DANGEROUS, all content in sd card will be erased.

echo "Umounting SD Card"
umount -f /media/sdcard
echo "Erasing and partitioning SD Card"
echo -e "d\nn\np\n1\n\n\nt\n7\nw" | fdisk /dev/mmcblk1
echo "Formating SD Card"
mkfs.exfat /dev/mmcblk1p1
echo "exFAT formating finished"
echo "Mounting SD Card"
mount -o remount,rw /media
mkdir -p /media/sdcard
mount.exfat -o rw /dev/mmcblk1p1 /media/sdcard
mount -o remount,ro /media
echo "END"