#!/bin/sh
# title=Format SD Card (FAT32) CAUTION!
# desc=Format the external sd card [fat32]. This is DANGEROUS, all content in sd card will be erased.

echo "Umounting SD Card"
umount -f /media/sdcard
echo "Erasing and partitioning SD Card"
echo -e "d\nn\np\n1\n\n\nt\nb\nw" | fdisk /dev/mmcblk1
echo "Formating SD Card"
mkfs -t vfat /dev/mmcblk1p1
echo "FAT32 formating finished"
echo "Mounting SD Card"
mount -o remount,rw /media
mkdir -p /media/sdcard
mount -t vfat -o rw /dev/mmcblk1p1 /media/sdcard
mount -o remount,ro /media
echo "END"