#!/bin/sh
# title=Format SD Card (EXT4) CAUTION!
# desc=Format the external sd card [ext4]. This is DANGEROUS, all content in sd card will be erased.
echo "Umounting SD Card"
umount -f /media/sdcard
echo "Erasing and partitioning SD Card"
echo -e "d\nn\np\n1\n\n\nt\n83\nw" | fdisk /dev/mmcblk1
echo "Formating SD Card"
echo -e "y" | mkfs -t ext4 /dev/mmcblk1p1
echo "EXT4 formating finished"
echo "Mounting SD Card"
mount -o remount,rw /media
mkdir -p /media/sdcard
mount -t ext4 -o rw /dev/mmcblk1p1 /media/sdcard
chmod 0777 -R /media/sdcard
mount -o remount,ro /media
echo "END"