#!/bin/sh

export HOME=`cat /etc/passwd |head -1 |cut -d':' -f 6`

# Restore the framebuffer to a working state
/usr/sbin/unlockvt > /dev/null

# Reset the console
/usr/bin/reset

# Disactivate the console on framebuffer
echo 0 > /sys/devices/virtual/vtconsole/vtcon1/bind

# Disable downscaling for future apps
if [ -f /sys/devices/platform/jz-lcd.0/allow_downscaling ] ; then
	echo 0 > /sys/devices/platform/jz-lcd.0/allow_downscaling
fi

# Restore the regular key map
if [ -f /sys/devices/platform/linkdev/alt_key_map ] ; then
	echo 0 > /sys/devices/platform/linkdev/alt_key_map
fi

# Stop the gravity sensor if it's loaded
/usr/sbin/gsensor --stop

# Source /etc/profile to set the environment variables
. /etc/profile

if [ -f /usr/local/sbin/frontend_start ]; then
	exec /usr/local/sbin/frontend_start
else
    if [ -f /media/data/.linker ]; then
    		rm -rf /usr/local/home/.gmenu2x/sections/applications/20_pyclock
		rm -rf /usr/local/home/.gmenu2x/sections/applications/25_Esoteric
		
		cp /usr/share/gmenu2x/sections/applications/20_clockod /usr/local/home/.gmenu2x/sections/applications/20_clockod
		cp /usr/share/gmenu2x/sections/applications/20_script /usr/local/home/.gmenu2x/sections/applications/20_script
		cp /usr/share/gmenu2x/sections/applications/25_DinguxCommander /usr/local/home/.gmenu2x/sections/applications/25_DinguxCommander
		cp /usr/share/gmenu2x/sections/applications/25_o2xiv /usr/local/home/.gmenu2x/sections/applications/25_o2xiv
		cp /usr/share/gmenu2x/sections/applications/30_terminal /usr/local/home/.gmenu2x/sections/applications/30_terminal
		cp /usr/share/gmenu2x/sections/applications/40_pg2test /usr/local/home/.gmenu2x/sections/applications/40_pg2test
		
		cp /usr/share/gmenu2x/sections/settings/10_poweroff /usr/local/home/.gmenu2x/sections/settings/10_poweroff
		cp /usr/share/gmenu2x/sections/settings/20_reboot /usr/local/home/.gmenu2x/sections/settings/20_reboot
		cp /usr/share/gmenu2x/sections/settings/40_alsamixer /usr/local/home/.gmenu2x/sections/settings/40_alsamixer
		cp /usr/share/gmenu2x/sections/settings/50_system_info /usr/local/home/.gmenu2x/sections/settings/50_system_info
		cp /usr/share/gmenu2x/sections/settings/60_network /usr/local/home/.gmenu2x/sections/settings/60_network
		
        	exec /usr/bin/gmenu2x
    else
        rm -rf /usr/local/home/.gmenu2x
        mkdir /usr/local/home/.gmenu2x/
        cp -r /usr/share/gmenu2x/* /usr/local/home/.gmenu2x/
        rm -rf /usr/local/home/.gmenu2x/gmenu2x
        touch /media/data/.linker
        exec /usr/bin/gmenu2x
    fi
fi
