#!/bin/sh

export HOME=`cat /etc/passwd |head -1 |cut -d':' -f 6`

# Restore the framebuffer to a working state
/usr/sbin/unlockvt > /dev/null

# Reset the console
/usr/bin/reset

# Disactivate the console on framebuffer
echo 0 > /sys/devices/virtual/vtconsole/vtcon1/bind

# Disable downscaling for future apps
if [ -f /sys/devices/platform/jz-lcd.0/allow_downscaling ] ; then
	echo 0 > /sys/devices/platform/jz-lcd.0/allow_downscaling
fi

# Restore the regular key map
if [ -f /sys/devices/platform/linkdev/alt_key_map ] ; then
	echo 0 > /sys/devices/platform/linkdev/alt_key_map
fi

# Stop the gravity sensor if it's loaded
/usr/sbin/gsensor --stop

# Source /etc/profile to set the environment variables
. /etc/profile

if [ -f /usr/local/sbin/frontend_start ]; then
	exec /usr/local/sbin/frontend_start
else
    if [ -f /media/data/.linker ]; then
		rm -rf /usr/local/home/.gmenu2x/sections/applications/20_pyclock
		rm -rf /usr/local/home/.gmenu2x/sections/applications/25_Esoteric
		
		if [ -f /usr/local/home/.gmenu2x/sections/applications/20_clockod ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/applications/20_clockod /usr/local/home/.gmenu2x/sections/applications/20_clockod
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/applications/20_script ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/applications/20_script /usr/local/home/.gmenu2x/sections/applications/20_script
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/applications/25_DinguxCommander ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/applications/25_DinguxCommander /usr/local/home/.gmenu2x/sections/applications/25_DinguxCommander
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/applications/25_o2xiv ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/applications/25_o2xiv /usr/local/home/.gmenu2x/sections/applications/25_o2xiv
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/applications/30_terminal ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/applications/30_terminal /usr/local/home/.gmenu2x/sections/applications/30_terminal
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/applications/40_pg2test ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/applications/40_pg2test /usr/local/home/.gmenu2x/sections/applications/40_pg2test
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/applications/50_Pixel-Fixer ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/applications/50_Pixel-Fixer /usr/local/home/.gmenu2x/sections/applications/50_Pixel-Fixer
		fi
		
		if [ -f /usr/local/home/.gmenu2x/sections/settings/10_poweroff ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/settings/10_poweroff /usr/local/home/.gmenu2x/sections/settings/10_poweroff
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/settings/20_reboot ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/settings/20_reboot /usr/local/home/.gmenu2x/sections/settings/20_reboot
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/settings/40_alsamixer ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/settings/40_alsamixer /usr/local/home/.gmenu2x/sections/settings/40_alsamixer
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/settings/50_system_info ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/settings/50_system_info /usr/local/home/.gmenu2x/sections/settings/50_system_info
		fi
		if [ -f /usr/local/home/.gmenu2x/sections/settings/60_network ]; then
		continue
		else
		cp /usr/share/gmenu2x/sections/settings/60_network /usr/local/home/.gmenu2x/sections/settings/60_network
		fi
		
		exec /usr/bin/gmenu2x
		
    else
		rm -rf /usr/local/home/.gmenu2x
		mkdir /usr/local/home/.gmenu2x/
		cp -r /usr/share/gmenu2x/* /usr/local/home/.gmenu2x/
		rm -rf /usr/local/home/.gmenu2x/gmenu2x
		rm -rf /usr/local/home/.gmenu2x/docs
		rm -rf /usr/local/home/.gmenu2x/skins
		rm -rf /usr/local/home/.gmenu2x/translations
		rm -rf /usr/local/home/.gmenu2x/user_manual
		rm -rf /usr/local/home/.gmenu2x/*.txt
		touch /media/data/.linker
		exec /usr/bin/gmenu2x
	fi
fi
