#!/bin/sh
# title=Restore home folder
# desc=Restore a backup to home folder, recover all your settings.
# author=eduardofilo

echo "Restoring home folder."
tar -xf /media/sdcard/home_backup.tar -C /media/data/local
echo ""
echo "Restoring done."
echo "END"